### ISSUE TITLE
Fix Readme instructions

### ISSUE THREAD

**Issue by GregorySchwing** [owensgroup/SlabHash#25]
Replace 
git submodule update
with
git submodule update --init --recursive

**Comment by maawad** [comment]
Hi @GregorySchwing, Thanks for reporting this. I have just followed the readme steps and compiled the code without problems. Which dependency required the `recursive`  option for you?

Here are the steps I took:
```shell
$ git clone https://github.com/owensgroup/SlabHash.git
$ cd SlabHash/
$ git submodule init
$ git submodule update
$ mkdir build && cd build
$ cmake -DSLABHASH_GENCODE_SM75=ON -DSLABHASH_GENCODE_SM35=OFF ..
$ make -j

$ ./bin/cmap_test
[==========] Running 6 tests from 3 test suites.
[----------] Global test environment set-up.
[----------] 1 test from ConcurrentMap
[ RUN      ] ConcurrentMap.Construction
[       OK ] ConcurrentMap.Construction (903 ms)
[----------] 1 test from ConcurrentMap (903 ms total)

[----------] 4 tests from BulkBuild
[ RUN      ] BulkBuild.IndividualSearch
[       OK ] BulkBuild.IndividualSearch (2 ms)
[ RUN      ] BulkBuild.BulkSearch
[       OK ] BulkBuild.BulkSearch (2 ms)
[ RUN      ] BulkBuild.IndividualCount
[       OK ] BulkBuild.IndividualCount (10 ms)
[ RUN      ] BulkBuild.IndividualDelete
[       OK ] BulkBuild.IndividualDelete (3 ms)
[----------] 4 tests from BulkBuild (18 ms total)

[----------] 1 test from UniqueBulkBuild
[ RUN      ] UniqueBulkBuild.IndividualCount
[       OK ] UniqueBulkBuild.IndividualCount (5 ms)
[----------] 1 test from UniqueBulkBuild (5 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 3 test suites ran. (926 ms total)
[  PASSED  ] 6 tests.
```

**Comment by GregorySchwing** [comment]
slaballoc and gtest

**Comment by GregorySchwing** [comment]
Actually, I didnt follow the instructions.  I tried to extend the SlabHash in my workflow by including the repo as a submodule via https://github.com/owensgroup/SlabHash.git and I must have missed the init step.

git submodule init

Your instructions work.  

On a separate issue, do you support a device side Multimap?

For example, the cuco library requires the user pass key-value pairs from the host side if more than one key exists with different values.

Does SlabHash allow a user to add multiple conflicting keys from the device and then retrieve a linked list/vector of all the elements with that key?

**Comment by maawad** [comment]
Great! Glad the instructions work.

Yes, SlabHash supports multimaps. The default [insert](https://github.com/owensgroup/SlabHash/blob/master/src/concurrent_map/warp/insert.cuh#L26) behavior maintains a multimap (it does not check for duplicate keys).  But the current implementation of [`searchKey`](https://github.com/owensgroup/SlabHash/blob/eec7135a3e5d40ba7fb9a7e88f7bd6d49abc4dee/src/concurrent_map/warp/search.cuh#L24) will only return the first value it finds. Implementing something like `find_all` is not that hard if you pass a buffer to where to store the values.

Do you mean a device-side API that you can use in your custom GPU kernel? Technically, these APIs exist but you will need to do a bit for work to call them directly. We have done something similar for a [dynamic graph](https://github.com/gunrock/gunrock/tree/dynamic-graph/gunrock/graph/dynamic_graph) data structure built on top of SlabHash.

**Comment by GregorySchwing** [comment]
Thank you for your message.  It's interesting to know this is what powers gunrock's dynamic graphs.  I am interested in graph algorithms, and I'll be referencing it in the future.  Thanks again,

Greg
